In [5]:
import numpy as np
N = int(input())
a = np.arange(0, N)
ans = a[::-1]
ans

10


array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [10]:
import numpy as np
N = int(input())
Ans1 = np.diag(np.arange(0, N, 1)[::-1], k=0)
Ans2 = np.sum(Ans1)

10


array([[9, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 8, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 7, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 6, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 5, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 4, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 3, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 2, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [15]:
import numpy as np
a = np.array( [ [4, 2, 1], [1, 3, 0], [0, 5, 4] ] )
b = np.array( [4, 12, -3] )
from numpy import linalg
linalg.solve(a, b)

array([ 0.46666667,  3.84444444, -5.55555556])

In [27]:
import numpy as np
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)

next_user_stats = np.array([0, 1, 2, 0, 0, 0])

def cosine(a, b):
    aLength = np.linalg.norm( a )
    bLength = np.linalg.norm( b )
    return np.dot(a, b) / (aLength * bLength)


similarity = cosine(users_stats[0], next_user_stats)
for i in users_stats[1::]:
    if 1 - cosine(i, next_user_stats) < similarity:
        similarity = 1 - cosine(i, next_user_stats)
        user = i
user

array([0, 1, 1, 0, 0, 0])